title: "Industrial Robotics Training Program"
description: "[Executive Training](https://www.dlsu.edu.ph/colleges/gcoe/academic-departments/manufacturing-engineering-management/)"
theme: jekyll-theme-minimal
markdown: kramdown
